In [3]:
from collections import Counter
import numpy as np
import pandas as pd
import torch

In [4]:
data = pd.read_csv('/data/high_risk_pregnant/pregnant/data/bishe_data_test/train.csv',low_memory=False)

In [5]:
y1 = data["premature"].values
y1_counts = Counter(y1)
y2 = data["low_BW"].values
y2_counts = Counter(y2)
y3 = data["macrosomia"].values
y3_counts = Counter(y3)
y4 = data["death"].values
y4_counts = Counter(y4)
y5 = data["malformation"].values
y5_counts = Counter(y5)
y6 = data["分娩方式"].values
y6_counts = Counter(y6)
y7 = data["产后出血"].values
y7_counts = Counter(y7)
y8 = data["SGA_S1"].values
y8_counts = Counter(y8)
y9 = data["LGA_S1"].values
y9_counts = Counter(y9)

In [74]:
y1_counts
y1_weight = torch.tensor([y1_counts.get(0) / y1_counts.get(1)])
y1_weight

tensor([11.0076])

In [75]:
y2_counts
y2_weight = torch.tensor([y2_counts.get(0) / y2_counts.get(1)])
y2_weight

tensor([14.1575])

In [76]:
y3_counts
y3_weight = torch.tensor([y3_counts.get(0) / y3_counts.get(1)])
y3_weight

tensor([26.8558])

In [77]:
y4_counts
y4_weight = torch.tensor([y4_counts.get(0) / y4_counts.get(1)])
y4_weight

tensor([279.5243])

In [78]:
y5_counts
y5_weight = torch.tensor([y5_counts.get(0) / y5_counts.get(1)])
y5_weight

tensor([78.1981])

In [79]:
y6_counts
y6_weight = torch.tensor([y6_counts.get(0) / y6_counts.get(1)])
y6_weight

tensor([1.1464])

In [80]:
y7_counts
y7_weight = torch.tensor([y7_counts.get(0) / y7_counts.get(1)])
y7_weight

tensor([127.4524])

In [6]:
y8_counts
y8_weights = torch.tensor([1.0 / np.log(y8_counts.get(i, 1)) for i in range(3)], dtype=torch.float)
y8_weights = torch.softmax(y8_weights,dim=0)
y8_weights

tensor([0.3291, 0.3340, 0.3368])

In [82]:
y9_counts
y9_weights = torch.tensor([1.0 / np.log(y9_counts.get(i, 1)) for i in range(3)], dtype=torch.float)
# y9_weights = torch.softmax(y9_weights,dim=0)
y9_weights

tensor([0.0665, 0.0781, 0.0858])